version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laraapp_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
