version: "3.1"
services:
  db:
    image: mysql:5.6
    restart: unless-stopped
    container_name: laravelapi_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravelapi
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - laravelapi
  app:
    depends_on:
      - db
    working_dir: /var/www/html
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    image: laravelapi
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    networks:
      - laravelapi
  composer:
    container_name: laravelapi_composer
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs
networks:
  laravelapi:
